services:
  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: unless-stopped
    networks:
      - app_network

  server:
    build: ./EchoServer
    container_name: tcp_math_server
    ports:
      - "33333:33333"
    volumes:
      - ./db/math_server.db:/app/math_server.db
    depends_on:
      - mailhog
    restart: unless-stopped
    networks:
      - app_network

networks:
  app_network:
    driver: bridge